vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-sg"
instance-name = "Tetris-gameapp"
key-name      = "eks-node-pair"
iam-role      = "Jenkins-iam-role"
